### ISSUE TITLE
[FE] 모든 와이어 프레임 작성

### ISSUE THREAD

**Issue by loocia1910** [loocia1910/senior-class#1]
### ISSUE
- Group: client
- Type: feature
- Detail: 모든 와이어 프레임을 오늘 안에 작성하도록 한다.

### TODO
- 랜딩페이지
- [x]  로그인
- [x]  회원가입
- [x]  강사지원

- my 페이지
- [x]  my 페이지
- [x]  회원 정보수정

- 클래스
- [x]  클래스 목록 페이지
- [x]  클래스 상세 페이지
- [x]  클래스 결제 페이지

### Estimated time
`7h`

**Comment by loocia1910** [comment]
내일 클래스 상세 페이지 결제하기 버튼 있는 부분, 클래스 결제 페이지 해야함
