### ISSUE TITLE
[FE] redux 공부하기

### ISSUE THREAD

**Issue by loocia1910** [loocia1910/senior-class#13]
### ISSUE
- Group: client
- Detail: 리덕스를 공부합니다.

### TODO
 - [x] 생활코딩 리덕스 영상 다 보기
 - [x]  redux 공식홈페이지 보기
 - [x]  레퍼런스 코드 보면서 모르는 단어 찾아보기
 
###Estimated time
12.30 ~ 12.31
