### ISSUE TITLE
[BE/FE] 회원가입 구현

### ISSUE THREAD

**Issue by loocia1910** [loocia1910/senior-class#18]
### ISSUE
- Group: client, server
- Type: feature
- Detail: 회원가입 페이지를 백엔드, 서버 파트 모두 구현한다.

### TODO
- [ ]  회원가입 컴포넌트 구현
    - [ ]  레이아웃
    - [ ]  리덕스를 사용하여 정보 저장하기. 회원 가입 성공 시 로그인이 되어야 함
    - 회원가입이 성공하면, 유저의 정보를 서버에서 받아 클라에서 상태로 저장
    - signup/success 페이지로 보내기
    - [ ]  유효성 검사 코드 수정

###Estimated time
3h
