### ISSUE TITLE
[BE] DB 스키마 작성

### ISSUE THREAD

**Issue by loocia1910** [loocia1910/senior-class#2]
### ISSUE
- Group: server
- Type:  feature
- Detail: DB 스키마 작성

### TODO
- [x] 필요한 테이블이 어떤 것이 있는지 작성
- [x] 각 테이블마다 필요한 필드 작성
- [x] RDBMS 데이터 모델 어떻게 작성하는지 공부
- [x]  DB 스키마 작성

### Estimated time
`3h`

**Comment by loocia1910** [comment]
3일 동안 고민한 끝에 드디어 끝났다.
물론 앞으로 수정 사항이 생길 것으로 예상된다. 하지만 잘 했다 김양현! 굿👍👩‍🦰👍

남은 오후는 DB 스키마를 구상하면서 생긴 에피소드를 블로깅으로 정리해야 겠다.
