### ISSUE TITLE
[BE/FE] 로그아웃 구현

### ISSUE THREAD

**Issue by loocia1910** [loocia1910/senior-class#20]
### ISSUE
- Group: client, server
- Type: feature
- Detail: 로그아웃 구현

### TODO
 - [x] 로그아웃 리듀서, createAsyncThunk 구현
  - [x]  로그아웃 버튼 클릭 핸들러
  - [x]  로그아웃 되면 안보이는 버튼 CSS

###Estimated time
2h
