### ISSUE TITLE
[BE] API 문서 작성 

### ISSUE THREAD

**Issue by loocia1910** [loocia1910/senior-class#3]
### ISSUE
- Group: server
- Type: feature
- Detail: API 문서 작성

### TODO
- [x] api 문서 레퍼런스 참고 
- [x] 페이지 별로 필요한 기능 작성
- [x] 필요한 기능 토대로 API문서 작성

### Estimated time
`4h`
