### ISSUE TITLE
[BE] 전체적인 환경 세팅 

### ISSUE THREAD

**Issue by loocia1910** [loocia1910/senior-class#4]
### ISSUE
- Group: server
- Type: feature
- Detail: 코드를 작성하기 이전에 작업 폴더 전체적인 틀을 만든다.

### TODO
- [x]  클라, 서버 전체적인 디렉토리 생성
    - [x]  어떤 폴더가 필요할지 작성
- [x]  서버 app.js 파일 만들기
- [x]  서버 controllers 폴더
    - [x]  안에 필요한 폴더 만들기
    - [x]  router 설정

### Estimated time
`3h`
