### ISSUE TITLE
[BE] Sequelize 모델 설정하기

### ISSUE THREAD

**Issue by loocia1910** [loocia1910/senior-class#7]
### ISSUE
- Group: server
- Type: feature
- Detail: Sequelize를 이용하여 모델을 생성하고 관계를 설정하여 DB 구축

### TODO
- [x] 모델 생성
- [x] 관계 설정하는 방법 구글링
- [x] 관계 설정
- [x] 관계 설정하는 법 블로깅
     - [x] belongsTo, hasOne, hasMany, belongsTo 가 무엇인지 정의
     - [x] migration, models 폴더가 무엇인지
     - [x] 관계 설정법

### Estimated time
`3h`
